### ISSUE TITLE
Jerry - Seeking behaviour of drone enemies

### ISSUE THREAD

**Issue by ronbonb0n** [ronbonb0n/GroupR#2]
Jerry will develop the seeking behaviours of the drones
- Drones roam from point to point
- If they detect the player sound an alarm 
- Refernce Unreal Behvaiour Tree video ( https://www.youtube.com/watch?v=iY1jnFvHgbE&t=513s )

**Comment by astro2049** [comment]
Using a state machine to switch between behaviors of AI drones:

- Idle (initial state)
- Patrol
- Look Around
- Chase
- Deactivated

reference: https://www.youtube.com/watch?v=nnrOhb5UdRc

**Comment by astro2049** [comment]
We're currently using a navmesh at the drones' height for random patrol locations and auto-pathing for drones.

**Comment by astro2049** [comment]
AI Sight:
Implemented by sphere overlap & ray cast, has a radius and angle.
reference: https://www.youtube.com/watch?v=j1-OyLo77ss

**Comment by astro2049** [comment]
Chase:
A drone will chase the player if the player is in sight.
reference: https://www.youtube.com/watch?v=wp8m6xyIPtE

**Comment by astro2049** [comment]
Master Kill Switch:
The switch kills all the drones when the player activates it.
The design is disabling the Nav Mesh Agent while having a Rigidbody with gravity on will make a drone fall from the sky, but the actual outcome is the drone will freeze still after. (TODO)
- Progress: 50%

**Comment by astro2049** [comment]
Demo: https://astro2049.github.io/StealthAI/build/index.html
