### ISSUE TITLE
James - Path Finding and Level Transitioning for world map 

### ISSUE THREAD

**Issue by ronbonb0n** [ronbonb0n/GroupR#3]
1) Setup Basic World Map
2) Design a path finding algorithm using preferred method 
3) Setup system to transition Scene to desired Level

**Comment by James-Joslin** [comment]
Adding additional proceduralisation to world map construction
- Currently takes an image
- Image is processed to 2D array of floats
- Float values matched to correct Prefab GameObject
- Chosen Prefab is placed (Still WIP) - **Now Completed**

**Comment by James-Joslin** [comment]
- Completed prefab placement
- Completed asset preperation for navmesh and navmesh construction within script
- Working on click and go player controller
- **Completed player click and go navigation**

**Comment by James-Joslin** [comment]
Starting top down camera control
- Panning completed
- Rotation completed
- Working on zoom
- Completed zoom - implementing min and max clamps - Done
- **All aspects completed**
- **Might be worth implementing an x rotation - needs discussion though to meet accessibility requirements**

**Comment by James-Joslin** [comment]
**Basic level transitioning completed**

**Comment by James-Joslin** [comment]
Expanded on procedural level tool built for world map to create dungeon levels - expanded from using single channel data to 3 channel rgb pixel data
