### ISSUE TITLE
Adarsh: Movement (Walking, Running, Crouching) and Stealth Behavior   

### ISSUE THREAD

**Issue by ronbonb0n** [ronbonb0n/GroupR#4]
1) Setup up Character model in Sample Scene
2) Program Movement using Unity Input System
3) Setup Trigger for Stealth using a Trigger box/sphere 
4) Setup System to change trigger size depending on movement

**Comment by adarsh046** [comment]
1. Character model for just now is a cylinder.
2. I've setup an input system to program the character movement and it's working perfectly fine now.
3. Setup the sphere trigger and made a child of our player.
4. Trigger sphere is now changing its size based on the movement and working fine.

**Comment by adarsh046** [comment]
Added cloak ability. When [E] is pressed, the player becomes invisible for 3 seconds. No footsteps (Collider size becomes zero) and drones can't see the player.
